const $=id=>document.getElementById(id),KEY='focus-flow-v2',oldKey='amos-focus-flow-v1';
const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)},today=()=>iso(new Date()),safe=s=>{const e=document.createElement('div');e.textContent=s||'';return e.innerHTML},uid=()=>Date.now()+Math.floor(Math.random()*10000);
let initial={tasks:[],profile:{name:'Student',goal:3,focus:25,theme:'light'},sessions:[],plan:[]};
try{const stored=JSON.parse(localStorage.getItem(KEY));if(stored){initial={...initial,...stored};if(/^(isaya( amos( mgasa)?)?|amos)$/i.test(initial.profile?.name?.trim()||''))initial.profile={...initial.profile,name:'Student'}}else{const legacy=JSON.parse(localStorage.getItem(oldKey)||'[]');initial.tasks=legacy.map(t=>({...t,id:String(t.id),minutes:Number(t.mins||t.minutes||50),notes:'',createdAt:Number(t.id)||Date.now()}))}}catch(e){}
let state=initial,filter='open',activeId=null,mode='focus',remaining=state.profile.focus*60,total=remaining,ticker=null,calendarDate=new Date();
localStorage.setItem(KEY,JSON.stringify(state));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const dayDiff=date=>Math.ceil((new Date(date+'T23:59:59')-new Date())/864e5);
const dueText=date=>{const d=dayDiff(date);return d<0?`${Math.abs(d)}d overdue`:d===0?'Due today':d===1?'Due tomorrow':`Due ${new Date(date+'T12:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}`};
const minsText=n=>n<60?`${n}m`:`${Math.floor(n/60)}h${n%60?` ${n%60}m`:''}`;
const sorted=list=>list.slice().sort((a,b)=>{if($('sort')?.value==='priority')return({high:0,medium:1,low:2}[a.priority]-{high:0,medium:1,low:2}[b.priority])||a.due.localeCompare(b.due);if($('sort')?.value==='newest')return(b.createdAt||0)-(a.createdAt||0);return a.done-b.done||a.due.localeCompare(b.due)||({high:0,medium:1,low:2}[a.priority]-{high:0,medium:1,low:2}[b.priority])});
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;$('toasts').append(el);setTimeout(()=>el.remove(),2800)}
function show(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.classList.contains('nav-item')&&b.dataset.view===name));$('sidebar').classList.remove('open');location.hash=name==='dashboard'?'':name;render()}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',e=>{if(b.tagName==='A')return;e.preventDefault();show(b.dataset.view)}));
function empty(title,copy=''){return `<div class="empty"><b>${title}</b>${copy}</div>`}
function taskCard(t,compact=false){return `<article class="task ${t.done?'done':''}" data-id="${t.id}">${compact?'':`<button class="task-check ${t.done?'checked':''}" data-check="${t.id}" aria-label="${t.done?'Mark incomplete':'Complete task'}">${t.done?'✓':''}</button>`}<div><strong>${safe(t.name)}</strong><div class="task-meta"><span>${safe(t.course)}</span><i class="${t.priority}">${t.priority}</i><span>${dueText(t.due)}</span><span>${minsText(Number(t.minutes))}</span></div></div>${compact?`<button class="button secondary" data-focus="${t.id}">Select</button>`:`<div class="task-actions"><button class="more" data-menu="${t.id}">•••</button><div class="task-menu" id="menu-${t.id}"><button data-focus="${t.id}">Start focus</button><button data-edit="${t.id}">Edit task</button><button data-delete="${t.id}">Delete</button></div></div>`}</article>`}
function render(){const open=state.tasks.filter(t=>!t.done),done=state.tasks.filter(t=>t.done),urgent=open.filter(t=>dayDiff(t.due)<=2),percent=state.tasks.length?Math.round(done.length/state.tasks.length*100):0,sessions=state.sessions.filter(s=>s.date===today());
  $('navCount').textContent=open.length;$('openStat').textContent=open.length;$('dueStat').textContent=urgent.length?`${urgent.length} due soon`:'Nothing urgent';$('minuteStat').textContent=minsText(open.reduce((a,t)=>a+Number(t.minutes),0));$('sessionStat').textContent=sessions.length;$('focusStat').textContent=`${sessions.reduce((a,s)=>a+s.minutes,0)} minutes focused`;$('percent').textContent=percent+'%';$('orbit').style.strokeDashoffset=320-(320*percent/100);
  const first=sorted(open)[0];$('heroTitle').textContent=first?`Next: ${first.name}`:state.tasks.length?'You cleared your list.':'Your day is wide open.';$('heroCopy').textContent=first?`${dueText(first.due)} · ${first.course} · about ${minsText(Number(first.minutes))}`:'Add your first task and Focus Flow will help you choose what to do next.';$('heroAction').textContent=first?'Start focusing':'Add your first task';$('heroAction').dataset.action=first?'hero-focus':'new';
  $('dashTasks').innerHTML=sorted(open).slice(0,4).map(t=>taskCard(t)).join('')||empty('You’re all caught up.','Enjoy the breathing room.');
  const query=$('search').value.toLowerCase();let visible=state.tasks.filter(t=>(filter==='all'||filter==='done'&&t.done||filter==='open'&&!t.done)&&(t.name+' '+t.course).toLowerCase().includes(query));$('allTasks').innerHTML=sorted(visible).map(t=>taskCard(t)).join('')||empty('No matching tasks.','Try another filter or add something new.');$('focusTasks').innerHTML=sorted(open).map(t=>taskCard(t,true)).join('')||empty('No open tasks.','Add a task to begin focusing.');
  $('streakDays').textContent=streak();renderCalendar();applyProfile();updateTimer();
}
function applyProfile(){const name=state.profile.name||'Student',first=name.split(' ')[0],salutation=`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}`;$('greeting').textContent=first.toLowerCase()==='student'?`${salutation}.`:`${salutation}, ${first}.`;$('todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();$('sideName').textContent=name;$('avatar').textContent=name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();document.body.classList.toggle('dark',state.profile.theme==='dark')}
function streak(){const dates=new Set(state.sessions.map(s=>s.date));let n=0,d=new Date();while(dates.has(iso(d))){n++;d.setDate(d.getDate()-1)}return n}
function openModal(id){$('taskForm').reset();$('taskId').value='';$('due').value=today();$('priority').value='medium';$('minutes').value='50';$('modalTitle').textContent='Add something to your plate';if(id){const t=state.tasks.find(x=>String(x.id)===String(id));if(!t)return;$('taskId').value=t.id;$('taskName').value=t.name;$('course').value=t.course;$('due').value=t.due;$('priority').value=t.priority;$('minutes').value=t.minutes;$('notes').value=t.notes||'';$('modalTitle').textContent='Update your task'}$('taskModal').showModal();setTimeout(()=>$('taskName').focus(),50)}
document.body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.action==='new')openModal();if(b.dataset.action==='close')$('taskModal').close();if(b.dataset.action==='hero-focus'){const first=sorted(state.tasks.filter(t=>!t.done))[0];if(first)selectFocus(first.id)}if(b.dataset.menu){document.querySelectorAll('.task-menu').forEach(m=>m.classList.toggle('open',m.id==='menu-'+b.dataset.menu&&!m.classList.contains('open')))}if(b.dataset.check)toggleTask(b.dataset.check);if(b.dataset.edit)openModal(b.dataset.edit);if(b.dataset.delete)deleteTask(b.dataset.delete);if(b.dataset.focus)selectFocus(b.dataset.focus)});
$('taskForm').addEventListener('submit',e=>{e.preventDefault();const id=$('taskId').value,data={id:id||String(uid()),name:$('taskName').value.trim(),course:$('course').value.trim(),due:$('due').value,priority:$('priority').value,minutes:Number($('minutes').value),notes:$('notes').value.trim(),done:false,createdAt:Date.now()};if(id){const old=state.tasks.find(t=>String(t.id)===id);data.done=old.done;data.createdAt=old.createdAt;state.tasks=state.tasks.map(t=>String(t.id)===id?data:t);toast('Task updated')}else{state.tasks.push(data);toast('Task added')}save();$('taskModal').close();render()});
function toggleTask(id){state.tasks=state.tasks.map(t=>String(t.id)===String(id)?{...t,done:!t.done}:t);save();render();toast('Task updated')}
function deleteTask(id){const t=state.tasks.find(x=>String(x.id)===String(id));if(t&&confirm(`Delete “${t.name}”?`)){state.tasks=state.tasks.filter(x=>String(x.id)!==String(id));if(String(activeId)===String(id))activeId=null;save();render();toast('Task deleted')}}
$('search').addEventListener('input',render);$('sort').addEventListener('change',render);$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;[...$('filters').children].forEach(x=>x.classList.toggle('active',x===b));render()});
function selectFocus(id){activeId=String(id);mode='focus';const t=state.tasks.find(x=>String(x.id)===activeId);remaining=total=(t?.minutes||state.profile.focus)*60;pause();show('focus');toast(`Ready to focus on ${t.name}`)}
function updateTimer(){const text=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('timer').textContent=text;$('miniTimer').textContent=text;$('timerProgress').style.strokeDashoffset=729*(1-remaining/total);const t=state.tasks.find(x=>String(x.id)===activeId);$('activeName').textContent=t?t.name:'Choose what you’re working on';$('activeMeta').textContent=t?`${t.course} · ${dueText(t.due)}`:'Select a task to connect it to this session.';$('miniTask').textContent=t?t.name:'Choose a task and start a distraction-free session.'}
function pause() {clearInterval(ticker);ticker=null;$('start').textContent=remaining<total?'Resume':'Start focus'}
function setMode(next){pause();mode=next;const lengths={focus:state.profile.focus,short:5,long:15};remaining=total=lengths[mode]*60;$('modeLabel').textContent={focus:'FOCUS SESSION',short:'SHORT BREAK',long:'LONG BREAK'}[mode];document.querySelectorAll('#modes button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));updateTimer()}
$('modes').addEventListener('click',e=>{if(e.target.dataset.mode)setMode(e.target.dataset.mode)});$('start').onclick=()=>{if(mode==='focus'&&!activeId)return toast('Choose a task first');if(ticker)return pause();$('start').textContent='Pause';ticker=setInterval(()=>{remaining--;updateTimer();if(remaining<=0){pause();if(mode==='focus'){state.sessions.push({date:today(),minutes:Math.round(total/60),taskId:activeId});save();toast('Focus session complete — great work!');setMode('short')}else setMode('focus');render()}},1000)};$('reset').onclick=()=>setMode(mode);$('skip').onclick=()=>setMode(mode==='focus'?'short':'focus');
function generatePlan(){const [sh,sm]=$('planStart').value.split(':').map(Number),[eh,em]=$('planEnd').value.split(':').map(Number),start=sh*60+sm,end=eh*60+em,block=+$('block').value,rest=+$('break').value;if(end<=start)return toast('End time must be after start time');let cursor=start,slots=[];for(const t of sorted(state.tasks.filter(x=>!x.done))){let left=Number(t.minutes);while(left>0&&cursor<end){const duration=Math.min(block,left,end-cursor);slots.push({type:'focus',start:cursor,duration,taskId:t.id,name:t.name,course:t.course});cursor+=duration;left-=duration;if(cursor+rest<end&&left>0){slots.push({type:'break',start:cursor,duration:rest});cursor+=rest}}if(cursor>=end)break}state.plan=slots;save();renderPlan();toast(slots.length?'Your plan is ready':'Add tasks before generating a plan')}
const clock=n=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
function renderPlan(){const focus=state.plan.filter(s=>s.type==='focus');$('planSummary').textContent=focus.length?`${focus.length} focus blocks · ${minsText(focus.reduce((a,s)=>a+s.duration,0))} of planned work`:'Generate a plan to see your timeline.';$('clearPlan').classList.toggle('hidden',!state.plan.length);$('timeline').innerHTML=state.plan.map(s=>`<div class="slot ${s.type}"><time>${clock(s.start)}</time><i class="rail"></i><div><b>${s.type==='break'?'Take a break':safe(s.name)}</b><span>${s.duration} min${s.course?' · '+safe(s.course):''}</span></div></div>`).join('')||empty('No plan yet.','Your generated schedule will appear here.')}
$('generate').onclick=generatePlan;$('clearPlan').onclick=()=>{state.plan=[];save();renderPlan()};
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());$('month').textContent=first.toLocaleDateString(undefined,{month:'long',year:'numeric'});let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const date=iso(d),list=state.tasks.filter(t=>t.due===date);html+=`<button class="day ${d.getMonth()!==m?'muted':''} ${date===today()?'today':''}" data-caldate="${date}"><span>${d.getDate()}</span>${list.slice(0,2).map(t=>`<i class="cal-task ${t.priority}">${safe(t.name)}</i>`).join('')}${list.length>2?`<small class="more-count">+${list.length-2} more</small>`:''}</button>`}$('monthGrid').innerHTML=html}
$('prev').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('next').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$('today').onclick=()=>{calendarDate=new Date();renderCalendar()};$('monthGrid').onclick=e=>{const b=e.target.closest('[data-caldate]');if(b){openModal();$('due').value=b.dataset.caldate}};
$('profileForm').onsubmit=e=>{e.preventDefault();state.profile.name=$('namePref').value.trim()||'Student';state.profile.goal=+$('goalPref').value;state.profile.focus=+$('focusPref').value;if(!activeId)setMode('focus');save();render();toast('Preferences saved')};
$('theme').onclick=()=>{state.profile.theme=state.profile.theme==='dark'?'light':'dark';save();applyProfile()};$('menu').onclick=()=> $('sidebar').classList.toggle('open');
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`focus-flow-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded')};
$('import').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.tasks)||!data.profile)throw Error();state={...initial,...data};save();render();toast('Data imported')}catch(err){toast('That file is not a valid Focus Flow backup')}};
$('clearData').onclick=()=>{if(confirm('Permanently delete all Focus Flow data in this browser?')){state={tasks:[],profile:{name:'Student',goal:3,focus:25,theme:'light'},sessions:[],plan:[]};activeId=null;pause();remaining=total=25*60;$('namePref').value=state.profile.name;$('goalPref').value=state.profile.goal;$('focusPref').value=state.profile.focus;save();renderPlan();render();toast('All data deleted')}};
window.addEventListener('hashchange',()=>show(location.hash.slice(1)||'dashboard'));document.addEventListener('click',e=>{if(!e.target.closest('.task-actions'))document.querySelectorAll('.task-menu').forEach(x=>x.classList.remove('open'))});
$('namePref').value=state.profile.name;$('goalPref').value=state.profile.goal;$('focusPref').value=state.profile.focus;$('due').value=today();renderPlan();show(location.hash.slice(1)||'dashboard');
